// lib/skill.ts

import { SkillItem } from "@/types/skill";

// Import the pre-downloaded data
// This will be generated by the build script
let skillsData: SkillItem[] = [];

try {
  skillsData = require("@/data/skills.json");
} catch (error) {
  console.warn("Skills data not found. Run npm run download-images first.");
}

export async function getSkillsFromNotion(): Promise<SkillItem[]> {
  return skillsData;
}
